Update for sapling

diff --git a/.scripts/ff-install b/.scripts/ff-install
--- a/.scripts/ff-install
+++ b/.scripts/ff-install
@@ -3,6 +3,7 @@
 set -euo pipefail
 
 DIR="$(realpath -- "$(dirname "${BASH_SOURCE[0]}")")"
+GHDIR="$(realpath -- "$DIR/../")"
 
 if [[ ! $# -eq 1 ]]; then 
   >&2 echo "Usage: $0 <branch-dir>"
@@ -11,8 +12,8 @@ fi
 
 PRDIR="$(git -C "$1" rev-parse --show-toplevel)"
 
-if [[ -e "$PRDIR/.envrc" || -e "$PRDIR/.vimrc" ]]; then 
-  >&2 echo "Error: $PRDIR already contains a .envrc or .vimrc"
+if [[ -e "$PRDIR/.envrc" || -e "$PRDIR/.vimrc" || -e "$PRDIR/.lockshaw.toml" ]]; then 
+  >&2 echo "Error: $PRDIR already contains a .envrc or .vimrc or .lockshaw.toml"
   exit 1
 fi
 
@@ -33,3 +34,5 @@ set path=lib/runtime/**,lib/**
 " set test target
 " let g:test_target = "utils-test"
 EOF
+
+cp "$DIR/template-lockshaw.toml" "$PRDIR/.lockshaw.toml"
